### ISSUE TITLE
clock examples does not work with firefox esr

### ISSUE THREAD

**Issue by djadala** [microo8/golymer#2]
Hi,
clock example display blank page with firefox esr, works fine with chromium.

inspector console show this:
```
unreachable code after return statement[Learn More]  clock.js:3392:2
TypeError: $global.customElements is undefined[Learn More]  clock.js:14330:3
	Define http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:14330:3
	main http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:14496:8
	$init http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:14515:9
	$go/$goroutine http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:1471:15
	$runScheduled http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:1511:7
	$schedule http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:1527:5
	$go http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:1503:3
	<anonymous> http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:14526:1
	<anonymous> http://localhost:8080/github.com/microo8/golymer/examples/clock/clock.js:2:2
unreachable code after return statement[Learn More]  clock.js:3392:2
```
I don't have good knowledge of JS and can't  figure where problem is, so filled this issue.

Regards

**Comment by djadala** [comment]
just discovered that you mention on reddit that it run only under chrome,
May be mention this also in readme.md ?

**Comment by microo8** [comment]
Sorry for the long wait ... 
Yes, on firefox there is no `window.customElement`. To create custom elements in firefox, use the [webcomponents polyfill](https://www.webcomponents.org/polyfills) (also polymer uses it).
There is also an [cdn](https://cdnjs.com/libraries/webcomponentsjs) for it. So just link to it in your html.

But I have not tested it out. I leave this issue open, to remind me that I must test golymer in firefox using the polyfills.

**Comment by tokamak-git** [comment]
Hello, Ive included the loader polyfill `https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.0.22/webcomponents-loader.js` seeing as it shall check and decide what needs to be put in.
but it is async. this leads to our register event occuring before the polyfill is loaded and ready.
temporary solution, suggested by [webcomponentsjs](https://github.com/WebComponents/webcomponentsjs), manually wrap the gopherjs generated code in `window.addEventListener('WebComponentsReady', function(e) { ... });`
Permanent solution:
1) add a `-wc` flag to gopherjs build that shall wrap everything in the above wrapper,
2) create a new loader script that is blocking
3) write the event call while creating the component. is this even possible?

Any opinions?

**Comment by microo8** [comment]
I've tried the `webcomponents-hi-sd-ce.js`, it isn't async, so all the things are loaded when `golymer` calls `Define`.
But firefox doesn't know about the `:host` selector, so all the shadow dom styles won't kick in.

1. golherjs is just an compiler from go to js, it doesn't care if you use it for webcomponents or node.js backend, so adding an new flag to it isn't an good idea
2. you can use `webcomponents-hi-sd-ce.js` to load everything, and it's blocking
3. gopherjs has the [js package](https://godoc.org/github.com/gopherjs/gopherjs/js) that can interact with the dom. so you can call the `Define` function for the clock elem like this:

```go
	js.Global.Get("window").Call("addEventListener", "WebComponentsReady",
		func() {
			err := golymer.Define(NewClockElem)
			if err != nil {
				panic(err)
			}
		})
```

I think this issue can be closed, the polyfills from the cdn work (just the shadow dom css doesn't)
